config/routes.rb
Tasklist::Application.routes.draw do
  resources :sections

  resources :tasks

  root 'tasks#index'

  get 'sections/:id/toggle_status' => 'sections#toggle_status', as: "sections_toggle_status"

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :sections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
     @task = Task.find(@section.task_id)
  end

  # GET /sections/new
  def new
    @section = Section.new
    @tasks = Task.all
  end

  # GET /sections/1/edit
  def edit
    @tasks = Task.all
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render action: 'show', status: :created, location: @section }
      else
        format.html { render action: 'new' }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    task = @section.task
    @section.destroy
    respond_to do |format|
      format.html { redirect_to task }
      # format.html { redirect_to task_path(id: task) }
      format.json { head :no_content }
    end
  end

  def toggle_status
    task = @section.task
    if @section.status
      @section.status = false
    else
      @section.status = true
    end

    @section.save

    respond_to do |format|
      format.html { redirect_to task }
      # format.html { redirect_to task_path(id: task) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:due_time, :contents, :task_id, :section_title, :status)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasklist</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1 class="main-title">TO DO LIST</h1>
<div id="wrapper">
<%= yield %>
</div>
</body>
</html>

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="type2">
  <tr>
    <th><%= f.label :section_title, "作業名" %></th>
    <td><strong><%= f.text_field :section_title %></strong></td>
  </tr>
  <tr>
    <th><%= f.label :due_time, "終了期限" %></th>
    <td><%= f.datetime_select :due_time ,:use_month_numbers => true %></td>
  </tr>
  <tr>
    <th><%= f.label :contents, "作業内容" %></th>
    <td><%= f.text_area :contents %></td>
  </tr>
  <tr>
    <th><%= f.label :task_id, "タスクのID" %></th>
    <td>
      <%= f.collection_select :task_id, @tasks, :id, :title %>
    </td>

  </tr>
  <!--<tr>
    <th><%= f.label :status, "進捗" %></th>
    <td><%= f.check_box :status %></td>
  </tr>-->
</table>
<br>
  <div class="actions">
    <%= f.submit '保存する' %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>作業の編集</h1>

<%= render 'form' %>

<%= link_to '戻る', @section %>
<%#= link_to '全作業一覧へ', sections_path %>

app/views/sections/index.html.erb
<h1>全作業一覧</h1>

<table>
  <thead>
    <tr>
      <th>タスク名</th>
      <th colspan="3">作業終了期限</th>
    </tr>
    <tr>
      <th>作業内容</th>
      <th>タスクID</th>
      <th>進捗</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td class="sectionTitle"><%= section.section_title %></td>
        <td colspan="3"><%= section.due_time.strftime('%Y年%m月%d日 %H:%M') %></td>
      </tr>
      <tr>
        <td><%= section.contents %></td>
        <td><%= section.task_id %></td>
        <td>
          <% if section.status %>
            済
          <% else %>
            未
          <% end %>
        </td>
        <td><%= link_to 'Show', section %><br><%= link_to 'Edit', edit_section_path(section) %><br><%= link_to '削除', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しく作業を追加する', new_section_path %>
<br><br>
<%= link_to 'タスク一覧に戻る', tasks_path %>

app/views/sections/new.html.erb
<h1>新しい作業</h1>

<%= render 'form' %>

<%= link_to '全作業一覧へ', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @task.title %>&emsp;<span>(ID: <%= @section.task_id %> )</span></h1>
<table class="type2">
	<tr>
		<th>作業名</th>
		<td><strong><%= @section.section_title %></strong></td>
	</tr>
	<tr>
		<th>終了期限</th>
		<td><%= @section.due_time %></td>
	</tr>
	<tr>
		<th>作業内容</th>
		<td><%= @section.contents %></td>
	</tr>
	<tr>
		<th>作業ID</th>
		<td><%= @section.id %></td>
	</tr>
	<!--<tr>
		<th>進捗</th>
		<td><%= @section.status %></td>
	</tr>-->
</table>
<br>
<%= link_to '編集する', edit_section_path(@section) %> |
<%= link_to '各タスクの一覧に戻る', task_path(id: @section.task_id) %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<table class="type2">
  <tr>
    <th><%= f.label :title, 'タスク名' %></th>
    <td><%= f.text_field :title %></td>
  </tr>
</table>
<br>
  <div class="actions">
    <%= f.submit '保存する' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク名変更</h1>

<%= render 'form' %>

<%= link_to 'このタスクの一覧へ', @task %> |
<%= link_to 'タスク一覧へ', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<table>
  <thead>
    <tr>
      <th>タスク名</th>
      <th>タスクId</th>
      <!--<th></th>-->
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, task_path(id: task.id) %></td>
        <td align="center"><%= task.id %></td>
        <!--<td><%= link_to 'このタスクの作業一覧を見る', task %></td>-->
        <td><%= link_to 'タスク名変更', edit_task_path(task) %></td>
        <td><%= link_to '削除', task, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規タスク作成', new_task_path %>
 |
<%= link_to '全作業の一覧へ', sections_path %>

app/views/tasks/new.html.erb
<h1>新しいタスク</h1>

<%= render 'form' %>

<%= link_to 'タスク一覧へ', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @task.title %>&emsp;<span>(ID: <%= @task.id %> )</span></h1>
<table>
    <% @task.sections.each do |section| %>
      <tr>
        <th><%= section.id %></th>
        <th>
          <% if section.status %>
            <%= link_to "未達成にする", sections_toggle_status_path(id: section.id) %>
          <% else %>
            <%= link_to "達成にする", sections_toggle_status_path(id: section.id) %>
          <% end %>
        <!-- <th><%= check_box_tag "section[status]", !section.status, section.status %></th> -->
        <td><%= link_to section.section_title, section_path(id: section.id) %></td>
        <td><%= section.due_time %></td>
        <td><%= link_to '削除', section_path(id: section.id), method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </table>
  <br><br>
<%#= link_to 'Edit', edit_task_path(@task) %><!-- |-->
<%= link_to 'タスク一覧へ戻る', tasks_path %> |
<%= link_to '作業を追加する', new_section_path %>